### PR TITLE
Fixing system handling of cycle creation when some plugin is not selected by the user

### LINKED ISSUE #106: Sistema não trata bem o não preenchimento do tipo do plugin da fase no cadastro de temas

### PR DESCRIPTION
**Pull request by erickzanardo**
This PR closes #106

### How was it before?

- when the user didn't selected any plugin type for the phase on the cycle creation and submitted the form, the system break

### What has changed?

- the system now returns an error message asking for the user to selected a plugin type

### What should I pay attention when reviewing this PR?

Nothing special

### Is this PR dangerous?

no

### CODE REVIEW

File: app/controllers/admin/cycles_controller.rb [hunk 1]
```diff
@@ -72,9 +72,22 @@ def new
 
   def create
```
Comment (guimello) [inline app/controllers/admin/cycles_controller.rb:73]: This is becoming troublesome. There are a lot of business logic here on the controller. We should consider moving these pieces to `use_cases`, `repositories`, etc. This will improve readability and mainly tests.

Perhaps add an issue so we can work on this later?

**Review by guimello — APPROVED** [review]
🚀  but we should consider drying the controller logic.

File: app/controllers/admin/cycles_controller.rb (hunk 1 above)
Comment (erickzanardo) [reply app/controllers/admin/cycles_controller.rb:73]: Yeah, since this PR is a simple correction, I will add another issue so we can work on this later

Comment (erickzanardo) [reply app/controllers/admin/cycles_controller.rb:73]: created #115
