### PR TITLE
Fixing final date on phases (issue 171)

### LINKED ISSUE #171: Acertar data final das fases

### PR DESCRIPTION
**Pull request by erickzanardo**
This PR closes #171

### How was it before?

 - when the phase was saved it's final date was being set to the start of the day

### What has changed?

 - now the phase final date is always set to the end of the day
 - improved the petition message for the remaining days

### What should I pay attention when reviewing this PR?

everthing

### Is this PR dangerous?

no

### CODE REVIEW

File: app/controllers/api/v2/entities/phase.rb [hunk 1]
```diff
@@ -46,7 +46,7 @@ class Phase < Grape::Entity
 
           property :final_date do
```
Comment (guimello) [inline app/controllers/api/v2/entities/phase.rb:47]: The `initial_date` is also ISO date time now

File: app/views/cycles/plugin_relations/petition.html.slim [hunk 2]
```diff
@@ -43,15 +43,19 @@ section#petition-index
...
-              | restantes para o encerramento
-            div.medium-padded
-              small= "As colaborações podem ser feitas até o dia #{@phase.final_date.strftime("%d/%m/%Y")}" 
+        - if @phase.in_progress?
+          .row.small-gap.remaining-days.bottom-info-container
+            .col-xs-12
+              .pull-left
+                i.icon-clock style="color: #{@cycle.color}"
+              div.medium-padded
+                - if @phase.remaining_days > 0
```
Comment (guimello) [inline app/views/cycles/plugin_relations/petition.html.slim:53]: You could add this to a a view helper and not to worry about doing this twice in this template.

File: lib/tasks/phases.rake [hunk 3]
```diff
@@ -0,0 +1,10 @@
+namespace :phases do
+  desc "Sets the final date of the phase to the end of the day"
+  task ends_on_the_end_of_the_day: :environment do |_, args|
```
Comment (guimello) [inline lib/tasks/phases.rake]: You are not using the block arguments, so you don't need to define them

`:environment do`

**Review by guimello — APPROVED** [review]
